### ISSUE TITLE
3.0版本问题

### ISSUE THREAD

**Issue by kan11jia28** [download-online-video/chrome-avgle-helper#11]
点击下载后，出现9a05f6d3-e5f7-4231-bef2-ed495f291a91让我保存，不知什么原因，打开后显示只有21KB，请问如何解决。
已经把windowslib复制到C盘users下

**Comment by vide0** [comment]
你下載的是視頻下載腳本文件, 在 git bash 中執行那個 `bash download-xxxxx.sh`就可以了
