### ISSUE TITLE
bestjavporn.com將會打算支援嗎？

### ISSUE THREAD

**Issue by bs-thomas** [download-online-video/chrome-avgle-helper#17]

**Comment by vide0** [comment]
或許

**Comment by vide0** [comment]
這個網站的下載方式很簡單，你可以在 DevTools 中直接找到下載連結，看上去像這樣的: `https://xxxx.xxxx.com/token=xxxxxxxxxxxxxxxx/xxxxxxxx/43.224.0.0/89/a/05/xxxxxxxxxx-480p.mp4`. 直接在新的 Tab 頁打開即可
