### ISSUE TITLE
Git cannot resolve host name timeout error

### ISSUE THREAD

**Issue by kelefeh** [download-online-video/chrome-avgle-helper#18]
Up until last week eveything worked normally. Now when I trying to download avgle video using git it just won't download and pops up error saying that timeout, cannot resolve host name. 

Base64 of m3u8 URL: aHR0cHM6Ly9pcDgxNTUxMjMyLmNkbi5xb29xbGV2aWRlby5jb20va2V5PXl5Z2dtNmRMUG91MVBJSlptS1lRbkEscz0sZW5kPTE1NzIyMzM3MDcsbGltaXQ9Mi9kYXRhPTE1NzIyMzM3MDcvc3RhdGU9SUFFT2FGUVotSFFzRDRwZi9yZWZlcmVyPWZvcmNlLC5hdmdsZS5jb20vcmVmdGFnPTU2MTA5NjQ0L21lZGlhPWhsc0EvMjMvMTc3LzcvNTY0MjA5ODcubTN1OA==
Extra options: avgle
Decoded m3u8 URL: https://ip81551232.cdn.qooqlevideo.com/key=yyggm6dLPou1PIJZmKYQnA,s=,end=1572233707,limit=2/data=1572233707/state=IAEOaFQZ-HQsD4pf/referer=force,.avgle.com/reftag=56109644/media=hlsA/23/177/7/56420987.m3u8
# downloading m3u8 file ...

10/28 10:14:30 [NOTICE] Downloading 1 item(s)

Then it comes out with error like this

10/28 10:17:01 [ERROR] CUID#7 - Download aborted. URI=https://ip81551232.cdn.qooqlevideo.com/key=yyggm6dLPou1PIJZmKYQnA,s=,end=1572233707,limit=2/data=1572233707/state=IAEOaFQZ-HQsD4pf/referer=force,.avgle.com/reftag=56109644/media=hlsA/23/177/7/56420987.m3u8
Exception: [AbstractCommand.cc:340] errorCode=2 Timeout.

Any ideas?
Thanks a lot

**Comment by vide0** [comment]
It seems like network problem. How to  diagnose:

1. open that m3u8 url link into your browser without proxy.
2. if u can download it then please try to refresh video page and get a new download command
3. if u CANT download it, please try to setup the proxy environment for your terminal.

**Comment by kelefeh** [comment]
> It seems like network problem. How to diagnose:
> 
> 1. open that m3u8 url link into your browser without proxy.
> 2. if u can download it then please try to refresh video page and get a new download command
> 3. if u CANT download it, please try to setup the proxy environment for your terminal.

seems like I need to setup a proxy but not sure what proxy address and port number to use, please help :(

**Comment by vide0** [comment]
@kelefeh Have you setup any proxy for the browser?

Suppose you set proxy address `127.0.0.1:1080` for the browser, then you need to execute these commands before you execute downloader:

```
export http_proxy=http://127.0.0.1:1080
export https_proxy=http://127.0.0.1:1080
```

**Comment by kelefeh** [comment]
Connecting to 127.0.0.1:1080
2019-11-12 14:50:36.561953 [INFO] [AbstractCommand.cc:368] CUID#7 - Restarting the download. URI=https://ip70258092.cdn.qooqlevideo.com/key=jopzrGF1UzhOp1l0DL2Cdw,s=,end=1573545812,limit=2/data=1573545812/state=IAEOaFQZO7H1jvEq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd6/177/3/191465533.m3u8
Exception: [AbstractCommand.cc:368] errorCode=1 URI=https://ip70258092.cdn.qooqlevideo.com/key=jopzrGF1UzhOp1l0DL2Cdw,s=,end=1573545812,limit=2/data=1573545812/state=IAEOaFQZO7H1jvEq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd6/177/3/191465533.m3u8
  -> [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:No connection could be made because the target machine actively refused it.


Still can't though, not sure what is the problem :(

**Comment by kelefeh** [comment]
> @kelefeh Have you setup any proxy for the browser?
> 
> Suppose you set proxy address `127.0.0.1:1080` for the browser, then you need to execute these commands before you execute downloader:
> 
> ```
> export http_proxy=http://127.0.0.1:1080
> export https_proxy=http://127.0.0.1:1080
> ```

Hi,

after i download the new version of avglehelper, and with your proxy setting, it works again!!
Thanks a lot :D

**Comment by vide0** [comment]
ok, u can follow this project, i will continue to update it
