### ISSUE TITLE
can't find processable m3u8 pattern

### ISSUE THREAD

**Issue by goaiworld** [download-online-video/chrome-avgle-helper#2]
this is some of my log from the extension. what could be the issue?
**log connection disconnected
Captured m3u8 request
  tabId: 3001
  GET https://ip72057797.ahcdn.com/key=zbVQR2riBm1c0kyCl9XgrA,s=,end=1548067249/state=Mw9I/reftag=72984513/media=hls/36/193/2/80622852.m3u8
Tab title: 人生で一番膣奥を貫かれたあの日から…。 光井ひかり JUY-060 - Avgle
Tab URL: https://avgle.com/video/JOcdVdyUMdd/人生で一番膣奥を貫かれたあの日から-光井ひかり-juy-060
Ignore: URL of m3u8 request is not matched with any pattern in PROCESSABLE_M3U8_PATTERN**

**Comment by vide0** [comment]
It will be patched in next commit
