### ISSUE TITLE
下载出错：line 389: ((: i<="gIilaFw&4Wq7y|aG : syntax error: operand expected (error token is ""gIilaFw&4Wq7y|aG ")

### ISSUE THREAD

**Issue by PlasmolysisMango** [download-online-video/chrome-avgle-helper#22]
/c/Users/Jack/bin/AvgleDownloader: line 389: ((: i<="gIilaFw&4Wq7y|aG : syntax error: operand expected (error token is ""gIilaFw&4Wq7y|aG ")

**Comment by kelefeh** [comment]
Me too line 389 error, need help

**Comment by vide0** [comment]
duplicated, #21
