### ISSUE TITLE
can't download missing file

### ISSUE THREAD

**Issue by caokhai1331999** [download-online-video/chrome-avgle-helper#24]
there is an error call operand expected( error token is "JR;B4m45%s|gX& ") when download .ts file. please help me!!

**Comment by caokhai1331999** [comment]
then it said all files have been downloaded eventhought it didn't download any files at all. after that an error appeared call invalid data found when processing input

**Comment by vide0** [comment]
<https://github.com/download-online-video/chrome-avgle-helper/issues/21>
