### ISSUE TITLE
Error while downloading file

### ISSUE THREAD

**Issue by ghost** [download-online-video/chrome-avgle-helper#25]
I get this error while trying to download a file. I previously used this program before and it worked but it suddenly has this error and I want to know if its the server side problem or not.

![image](https://user-images.githubusercontent.com/59027633/71109810-fc82db00-2200-11ea-9e86-0393a3786972.png)

**Comment by caokhai1331999** [comment]
i have the same error:(

**Comment by vide0** [comment]
<https://github.com/download-online-video/chrome-avgle-helper/issues/21>
