### ISSUE TITLE
OSX cannot install

### ISSUE THREAD

**Issue by abzhaobo** [download-online-video/chrome-avgle-helper#28]
```
[.] copying `Avgle` ...
cp: Avgle: No such file or directory
[-] FATAL: Copy `Avgle` failed!
exit with code 1
```
The installation failed with this message. What could be the problem? Thanks!

**Comment by vide0** [comment]
`./instal.sh` is deprecated. you just need install this chrome extension. and `brew install ffmpeg aria2`.

Then click the "Download Video Downloader" item in the popup menu of the extension.
then `bash download-xxxxxx.sh`

**Comment by xiaoluimore** [comment]
> `./instal.sh` is deprecated. you just need install this chrome extension. and `brew install ffmpeg aria2`.
> 
> Then click the "Download Video Downloader" item in the popup menu of the extension.
> then `bash download-xxxxxx.sh`

Hey im using git bash on Windows 10, can you enlight me?

**Comment by jiangshan529** [comment]
Hi, I can get the download.sh from webpage and I can download all ts files successfully. However, I cannot converge the ts files to mp4 files. Can you help me to deal with this?
Thanks!
