### ISSUE TITLE
不能正常使用了

### ISSUE THREAD

**Issue by lbbboy** [download-online-video/chrome-avgle-helper#3]
视频下载地址不是每次都能出现。要出现人机验证通过后才会出现。
运行下载命令下载目录没有TS文件，在bin目录内有m3u8文件视频时间是倒着的。
win10 系统下。

**Comment by vide0** [comment]
1. 人機檢測暫時無法解決
2. Avgle更新了，下一個commit解決
3. m3u8 時間是倒序?

**Comment by lbbboy** [comment]
> 1. 人機檢測暫時無法解決
> 2. Avgle更新了，下一個commit解決
> 3. m3u8 時間是倒序?

commit 搜了一圈不知道哪里下，能告知哪里下么谢谢。

**Comment by vide0** [comment]
@lbbboy lol, 我的意思是我今天提交的 下一條 commit (next commit) 會解決這個問題.

目前 Avgle 更新導致的 bug 已經在最新的 2.0.0 裏面解決了. 你可以嘗試一下

**Comment by lbbboy** [comment]
> @lbbboy lol, 我的意思是我今天提交的 下一條 commit (next commit) 會解決這個問題.
> 
> 目前 Avgle 更新導致的 bug 已經在最新的 2.0.0 裏面解決了. 你可以嘗試一下

2.0.0 版本 linux 下可以下载 合并命令出错
win TS文件找不到

**Comment by bdingdong** [comment]
@lbbboy `error: expected max number of video fragments is: avgle-_8vrrrC1Zrr` 是因为要你再terminal paste的code有问题，比方说在avgle上叫你paste

```
AvgleDownloader decode=true name=HND-617 url=aHR0cHM6Ly9nb29xbGV2aWRlby54eXovcGxheWJhY2svZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SmxlSEJwY21WelFYUWlPakUxTkRnek9UY3dNVGtzSW5WelpYSkpVQ0k2SWpVd0xqUTJMakV4TkM0eU5ETWlMQ0p3Y205NGVXbHVaMVZTVEVOeWVYQjBTbk52YmlJNkludGNJbU4wWENJNlhDSTFkWEUwYkc5bVRGUllhbXRpY20xaFYxUXhaRWRoVVZobFJsUk1WMlpuVm5WdmVtSkdibmRJV1dnd04xazBiRnB6YW5wQlVqVlJTVmhvTmtKRGFrUnhRMUpzZWxZd1NqQndhRmxWWkd0VVRYSlhSM0JFUTJGT1JrcGpURkVyVm1aa0szRk1kM2x3VjBGTldXeHhSRTVLWlVwVlFWeGNYQzlJVkVGVk1VdFFjMFpLWWtveU1YVklUbmRMZW05RmVsTkRNVEJTWm05WU5YTkNabTFSVWt0RmJHOXVkbFZ1YkZOY1hGd3ZlWEZPVVc1WVFXY3pkRlZWVTFnM1FuZG1kVFJhWlVkS2FqbHdhSGMwWnpNM1hGeGNMM1JJZWtvek5IaFZWMGRrYTFKblBUMWNJaXhjSW1sMlhDSTZYQ0prTlRoa1lUUXpNVFk0WXpVNE5qVmxNRFJsTVRRMFpUUTBOV05oTXpjNE9Gd2lMRndpYzF3aU9sd2lZamN3WlRkaVpEVTRPRFEwTXpjeU5sd2lmU0o5LkFCMnhISkJnd3pVRHdUbjZMTDVyNUdVWjFGbU9zOWJEa3hlT3NiamJSVkU=;
Avgle HND-617; # combine video files
```
最后的command是`Avgle HND-617`，而这个应该只是`Avgle`。即使你现在用Avgle就能combine所有的.ts file.

**Comment by lbbboy** [comment]
win下tmp还是没有ts文件。
linux下command 文件 要在文件名称上加引号解决了，扩展生成的名称是否能加入自动加引号？
Avgle `HND-617`; # combine video files

**Comment by lbbboy** [comment]
``` 
Avgle `HND-617`; # combine video files
```
linux下文件名加引号解决了问题。能否在 Download Command 生成的代码能自动加上？

**Comment by vide0** [comment]
@ShinGetter123 
Do you means `M3U8_URL_BASE64` in bash script named `AvgleDownloader`?
It is not extracted from the web page. It is captured from network traffic event in Google Chrome

**Comment by vide0** [comment]
@lbbboy 

如果合并失败, 可以尝试删除临时资料夹(类似: `.tmp-avgle-_8vrrrC1Zrr ~`) 和 m3u8 文件, 然后重新执行一下 `AvgleDownloader`. 如果下载中途失败了, 请尝试重新执行 `AvgleDownloader`. 然后再执行 `Avgle` 进行合并.

如果 Windows 下仍然有问题, 请把相关 URL, windows-libs 目录下的结构反馈一下

**Comment by lbbboy** [comment]
> @lbbboy
> 
> 如果合并失败, 可以尝试删除临时资料夹(类似: `.tmp-avgle-_8vrrrC1Zrr ~`) 和 m3u8 文件, 然后重新执行一下 `AvgleDownloader`. 如果下载中途失败了, 请尝试重新执行 `AvgleDownloader`. 然后再执行 `Avgle` 进行合并.
> 
> 如果 Windows 下仍然有问题, 请把相关 URL, windows-libs 目录下的结构反馈一下

win下没有ST文件是因为我没装Aria2后面细看了说明现在一切正常。用Avgle直接合并了。
同目录下有多个m3u8。合并就会提示文件过多。 avgle m3u8名称又会提示找不到文件。这个名称应该加什么引号么。

**Comment by lbbboy** [comment]
```
$ Avgle spermmania-108
 1.Concat seg-*-v1-a1.ts you downloaded from avgle
 2.Convert ts file to mp4 using ffmpeg
 3.Rename mp4 file name according to folder it located
 4.Remove All temporary *.ts files if you don't need them anymore
===============================================
/f/test/.tmp-avgle~spermmania-108 /f/test
# Found avgle ts files, max ts file number is: 127
  error: expected max number of video fragments is: spermmania-108

```
```
$ Avgle
/f/test/.tmp-avgle~spermmania-108 /f/test
# Found avgle ts files, max ts file number is: 127
# Confirmed all *.ts files are existed
# Generating list file for ffmpeg ...

# Concat file concat.list generated
# Converting ts file to mp4 files ...
# Converted concat.list file to ../spermmania-108.mp4
/f/test

Do you want to delete temp directory and m3u8 file ?
Confirm (y/n) > y
# Deleting temp directory .tmp-avgle~spermmania-108 ...
# Deleting m3u8 file spermmania-108.m3u8 ...
# All temporary files are deleted!
# Finish!
```

**Comment by vide0** [comment]
@lbbboy  我今天也发现了, 最新版我已经修正了. 如果是有多个 m3u8 文件, 那个就执行: `Avgle xxx.m3u8` 或是 `Avgle xxx`

**Comment by lbbboy** [comment]
@vide0 
测试了下，能否生成下载代码加上引号不然还是出错。

```
Avgle `xxx`

**Comment by vide0** [comment]
@lbbboy 
你是在哪个系统上遇到的问题, 然后你加上的引号是哪一个? 因为如果是数字1旁边的那个引号, 在 Linux/OSX上是肯定不行的

**Comment by lbbboy** [comment]
> @lbbboy
> 你是在哪个系统上遇到的问题, 然后你加上的引号是哪一个? 因为如果是数字1旁边的那个引号, 在 Linux/OSX上是肯定不行的

win10
这种文件名加了才行

```
Avgle `spermmania-108`

**Comment by vide0** [comment]
@lbbboy Windows 10 上的 `Git Bash` 吗？还是其他的

**Comment by lbbboy** [comment]
@vide0 win10 Git Bash
