### ISSUE TITLE
使用aria2c下载时候，tmp文件只有一个log，然后会在目标文件显示一个100k左右的小文件后停止下载

### ISSUE THREAD

**Issue by zqy767** [download-online-video/chrome-avgle-helper#4]
ubuntu 18.04系统，是我aria2c设置有问题，还是什么情况？

**Comment by HBJ233** [comment]
还需要输入命令
`Avgle XXX; # combine video `
将所有文件转为一个文件

**Comment by vide0** [comment]
贴一下 `AvgleDownloader` 的输出日志.

检查网络是否OK, 下载是否出现了 403
