### ISSUE TITLE
Error: input m3u8 url is invalid.

### ISSUE THREAD

**Issue by terrybossy1122** [download-online-video/chrome-avgle-helper#5]
Hello, I’m using Chrome plugin to get Base64 url of m3u8. Then I feed the acquired url to the AvgleDownloader.sh script (I’m on Windows 7 64) but get “Extra options: avgle base64: invalid input Error: input m3u8 url is invalid!" What am I doing wrong? Also, when I’m trying to download m3u8 by any other methods I get Error 403. Does it have to do something with the capcha protection? Are there are any other means to circumvent this kind of security? Thanks.

**Comment by vide0** [comment]
Can you paste the downloading command you got from this Chrome extension in here? (Or the output of the `AvgleDownloader`)

Btw, you have been passed the capcha protection if you got m3u8 url. And the downloader script can resolve the 403 problem automatically.

**Comment by ikelca** [comment]
i got same issue

`bash-5.0$ ./AvgleDownloader name=901662 url=“https://ip110139021.cdn.qooqlevideo.com/key=aNCSxk6FmiTyQp8PQiHBOg,s=,end=1555974022,limit=2/data=1555974022/state=QOeI/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd2/177/6/56410876.m3u8”
     _                _            
    / \    __  __ _  | |   ___    
   / _ \  / / / _` | | |  / _ \  
  / ___ \/ / | (_| | | | |  __/   
 /_/   \__/   \__, | |_|  \___|   Downloader
              |___/                
 Usage: AvgleDownloader [option=value ...]
 Updated date: 2019-01-30

🚀  aria2 mode is enabled! 🚀
Video name: 901662
Base64 of m3u8 URL: “https://ip110139021.cdn.qooqlevideo.com/key=aNCSxk6FmiTyQp8PQiHBOg,s=,end=1555974022,limit=2/data=1555974022/state=QOeI/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd2/177/6/56410876.m3u8”
Extra options: avgle
Invalid character in input stream.
  Error:   input m3u8 url is invalid!

bash-5.0$ 
`

**Comment by ikelca** [comment]
ok, it seems error is from base64 --decode

**Comment by vide0** [comment]
@ikelca It seems like you get invalid download command (the m3u8 url you got is not base64 encoded string) from Chrome extension.Is your Avgle helper extension latest. Because I can't reproduce this bug, And the download command What I saw is like this:

![screenshot](https://user-images.githubusercontent.com/45325881/56564288-4834a480-65e0-11e9-8594-13bf2a238b8b.png)

**Comment by ikelca** [comment]
my mistake, you are correct, the url i got was decrypted one, thats why i got invalid error, as soon as I put original encrypted url, it worked.

**Comment by imammubin** [comment]
@vide0 i follow yout command, the result is:
base64: command not found
