### ISSUE TITLE
Download error: CUID# download aborted

### ISSUE THREAD

**Issue by jamiechoi1995** [download-online-video/chrome-avgle-helper#6]
![image](https://user-images.githubusercontent.com/13494034/55284503-8efcf900-53aa-11e9-8da8-65c93abcd7a0.png)

I got the following error for all segments of the video.

However, I can successfully download other video.

**Comment by vide0** [comment]
You mentioned the `403` error.
Possible reasons:

**Comment by jamiechoi1995** [comment]
This may due to may cmd does not have a proxy, I solve it by run this command on my VPS.
