### ISSUE TITLE
下载时出错了

### ISSUE THREAD

**Issue by gsons** [download-online-video/chrome-avgle-helper#8]
无法解密指定的数据

**Comment by vide0** [comment]
麻煩提供一下相關的輸出

**Comment by gsons** [comment]
Video name: 22
Base64 of m3u8 URL: aHR0cHM6Ly9pcDE0MjIzNjQ0Mi5jZG4ucW9vcWxldmlkZW8uY29tL2tleT1SZWQ1SzlIaWpLK2phY0NpYzNmWmpBLHM9LGVuZD0xNTYwNzA4NTkxLGxpbWl0PTIvZGF0YT0xNTYwNzA4NTkxL3N0YXRlPXVSYXQvcmVmZXJlcj1mb3JjZSwuYXZnbGUuY29tL3JlZnRhZz01NjEwOTY0NC9tZWRpYT1obHNBL3NzZDMvMTc3LzUvMTcxODY5MzE1Lm0zdTg=
Extra options: avgle
Decoded m3u8 URL: https://ip142236442.cdn.qooqlevideo.com/key=Red5K9HijK+jacCic3fZjA,s=,end=1560708591,limit=2/data=1560708591/state=uRat/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd3/177/5/171869315.m3u8
downloading m3u8 file ...

06/17 01:00:56 [NOTICE] Downloading 1 item(s)
[#422ef4 48KiB/160KiB(29%) CN:1 DL:53KiB ETA:2s]
06/17 01:01:02 [ERROR] WinTLS: Failed to decrypt a message! Error: 无法解密指定的数据


紧接着程序就exit了

**Comment by vide0** [comment]
大陸用戶嗎？如果是請檢查一下代理，有可能被 ban 了，或者是你系統的HTTPS證書問題。

順帶一提，你這個是在 Windows 的 Git Bash 中使用的嗎

**Comment by kelefeh** [comment]
我也是，直到上个星期前还可以正常使用，现在跟楼主有一样的问题

**Comment by vide0** [comment]
@kelefeh 檢查系統的代理設定，如果中途下載失敗，則可以嘗試刷新視頻頁面，然後獲取新的下載命令。新的下載命令在相同的資料夾內執行，則中斷前的下載到的片段會被繼續使用，所以不用擔心鑰從頭來過。
